### ISSUE TITLE
Allow document files to be saved to gallery (docx, pdf etc.)

### ISSUE THREAD

**Issue by jabirmayar** [flowmobile/add_to_gallery#1]
Hello, thank you for this nice package. I know the name says it all but can you make some changes to copy other format files like pdf , Docx, etc to documents or download folder? I tried adding extensions to the get file type but it won't work. Thank you in advance.

**Comment by oodavid** [comment]
Hi @jabirmayar, thanks for the feature request. I'm busy refactoring the package to make it ready for Android 10 and 11.

This feature ties in with our requirements, so it's very likely that we'll add this functionality.

Sorry I can't commit to a timeline yet :)

**Comment by jabirmayar** [comment]
Thank you for your response. Hope it will be soon, looking forward to it.
