### ISSUE TITLE
After upgrading to 3.24.0 the android release build is broken on several packages giving the error "AAPT: error: resource android:attr/lStar not found."

### ISSUE THREAD

**Issue by Nashev** [flowmobile/add_to_gallery#10]
See further in https://github.com/flutter/flutter/issues/153281

So please update your compileSdk = 34 anstead of compileSdkVersion = 34 (according to https://developer.android.com/google/play/requirements/target-sdk)

**Comment by oodavid** [comment]
We've just release 0.4.0 to use `compileSdk = 34`.

https://pub.dev/packages/add_to_gallery

Feel free to re-open this issue if this doesn't fix your problem.
